# ==============================================================================
# DATABASE SECRETS
# ==============================================================================
# Purpose: Store PostgreSQL credentials securely
# - Used by all microservices to connect to PostgreSQL
# - Base64 encoded values
# - Should be stored in a secret management system in production
# ==============================================================================

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: observability
  labels:
    app: postgres
    component: database
type: Opaque
data:
  # postgres / base64 encoded
  POSTGRES_USER: cG9zdGdyZXM=
  
  # postgres / base64 encoded
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  
  # postgres / base64 encoded
  POSTGRES_DB: cG9zdGdyZXM=
  
  # postgres:5432 / base64 encoded
  DB_HOST: cG9zdGdyZXM=
  
  # 5432 / base64 encoded
  DB_PORT: NTQzMg==
  
  # disable / base64 encoded
  DB_SSLMODE: ZGlzYWJsZQ==

---
# ==============================================================================
# DATABASE CONNECTION STRINGS
# ==============================================================================
# Purpose: Pre-constructed connection strings for each database
# ==============================================================================

apiVersion: v1
kind: Secret
metadata:
  name: database-urls
  namespace: observability
  labels:
    app: database
    component: connection-strings
type: Opaque
data:
  # postgresql://postgres:postgres@postgres:5432/userdb?sslmode=disable
  USER_DB_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzOjU0MzIvdXNlcmRiP3NzbG1vZGU9ZGlzYWJsZQ==
  
  # postgresql://postgres:postgres@postgres:5432/productdb?sslmode=disable
  PRODUCT_DB_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzOjU0MzIvcHJvZHVjdGRiP3NzbG1vZGU9ZGlzYWJsZQ==
  
  # postgresql://postgres:postgres@postgres:5432/inventorydb?sslmode=disable
  INVENTORY_DB_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzOjU0MzIvaW52ZW50b3J5ZGI/c3NsbW9kZT1kaXNhYmxl
  
  # postgresql://postgres:postgres@postgres:5432/paymentdb?sslmode=disable
  PAYMENT_DB_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzOjU0MzIvcGF5bWVudGRiP3NzbG1vZGU9ZGlzYWJsZQ==

---
# ==============================================================================
# REDIS SECRET
# ==============================================================================
# Purpose: Redis connection credentials
# ==============================================================================

apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: observability
  labels:
    app: redis
    component: cache
type: Opaque
data:
  # redis:6379 / base64 encoded
  REDIS_ADDR: cmVkaXM6NjM3OQ==
  
  # empty password / base64 encoded
  REDIS_PASSWORD: ""
  
  # 0 / base64 encoded (default database)
  REDIS_DB: MA==

