{{- if .Values.apiGateway.enabled }}
# ==============================================================================
# API GATEWAY - DEPLOYMENT
# ==============================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.apiGateway.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.apiGateway.name }}
    component: gateway
    tier: edge
spec:
  replicas: {{ .Values.apiGateway.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ .Values.apiGateway.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.apiGateway.name }}
        component: gateway
        tier: edge
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.apiGateway.service.port }}"
        prometheus.io/path: "/metrics"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - {{ .Values.apiGateway.name }}
                topologyKey: kubernetes.io/hostname
      
      initContainers:
        - name: wait-for-redis
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z redis 6379; do echo waiting for redis; sleep 2; done;']
        - name: wait-for-user-service
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z user-service 8080; do echo waiting for user-service; sleep 2; done;']
        - name: wait-for-product-service
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z product-service 8081; do echo waiting for product-service; sleep 2; done;']
        - name: wait-for-inventory-service
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z inventory-service 8082; do echo waiting for inventory-service; sleep 2; done;']
        - name: wait-for-payment-service
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z payment-service 8083; do echo waiting for payment-service; sleep 2; done;']
      
      containers:
        - name: {{ .Values.apiGateway.name }}
          image: {{ .Values.global.imageRegistry }}/{{ .Values.apiGateway.image.repository }}:{{ .Values.apiGateway.image.tag }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.apiGateway.service.port }}
              protocol: TCP
          env:
            - name: GATEWAY_PORT
              value: "{{ .Values.apiGateway.service.port }}"
            - name: OTEL_SERVICE_NAME
              value: "api-gateway"
            - name: USER_SERVICE_URL
              value: "http://user-service:8080"
            - name: PRODUCT_SERVICE_URL
              value: "http://product-service:8081"
            - name: INVENTORY_SERVICE_URL
              value: "http://inventory-service:8082"
            - name: PAYMENT_SERVICE_URL
              value: "http://payment-service:8083"
          envFrom:
            - secretRef:
                name: redis-secret
            - configMapRef:
                name: app-config
          resources:
            {{- toYaml .Values.apiGateway.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
            failureThreshold: 30
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop: ["ALL"]
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 15"]
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
      terminationGracePeriodSeconds: 30

---
# ==============================================================================
# API GATEWAY - SERVICE (LoadBalancer)
# ==============================================================================
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apiGateway.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.apiGateway.name }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.apiGateway.service.port }}"
spec:
  type: {{ .Values.apiGateway.service.type }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - name: http
      port: {{ .Values.apiGateway.service.port }}
      targetPort: http
      {{- if and (eq .Values.apiGateway.service.type "NodePort") .Values.apiGateway.service.nodePort }}
      nodePort: {{ .Values.apiGateway.service.nodePort }}
      {{- end }}
      protocol: TCP
  selector:
    app: {{ .Values.apiGateway.name }}
  {{- if eq .Values.apiGateway.service.type "LoadBalancer" }}
  loadBalancerSourceRanges:
    - 0.0.0.0/0
  {{- end }}

---
# ==============================================================================
# API GATEWAY - HORIZONTAL POD AUTOSCALER
# ==============================================================================
{{- if .Values.apiGateway.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.apiGateway.name }}-hpa
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.apiGateway.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.apiGateway.name }}
  minReplicas: {{ .Values.apiGateway.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.apiGateway.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.apiGateway.autoscaling.targetCPUUtilizationPercentage }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 50
          periodSeconds: 15
        - type: Pods
          value: 1
          periodSeconds: 15
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
        - type: Pods
          value: 2
          periodSeconds: 15
      selectPolicy: Max
{{- end }}

---
# ==============================================================================
# API GATEWAY - POD DISRUPTION BUDGET
# ==============================================================================
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.apiGateway.name }}-pdb
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.apiGateway.name }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ .Values.apiGateway.name }}

---
# ==============================================================================
# API GATEWAY - SERVICE MONITOR
# ==============================================================================
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.apiGateway.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.apiGateway.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.apiGateway.name }}
  endpoints:
    - port: http
      interval: 15s
      path: /metrics
      scheme: http

{{- end }}
