{{- if .Values.inventoryService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.inventoryService.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.inventoryService.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.inventoryService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.inventoryService.name }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.inventoryService.service.httpPort }}"
    spec:
      containers:
        - name: {{ .Values.inventoryService.name }}
          image: {{ .Values.global.imageRegistry }}/{{ .Values.inventoryService.image.repository }}:{{ .Values.inventoryService.image.tag }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.inventoryService.service.httpPort }}
              name: http
            - containerPort: {{ .Values.inventoryService.service.grpcPort }}
              name: grpc
          env:
            - name: HTTP_PORT
              value: "{{ .Values.inventoryService.service.httpPort }}"
            - name: GRPC_PORT
              value: "{{ .Values.inventoryService.service.grpcPort }}"
            - name: DB_NAME
              value: "inventorydb"
          envFrom:
            - secretRef:
                name: postgres-secret
            - secretRef:
                name: kafka-secret
            - configMapRef:
                name: app-config
          resources:
            {{- toYaml .Values.inventoryService.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.inventoryService.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.inventoryService.service.type }}
  ports:
    - port: {{ .Values.inventoryService.service.httpPort }}
      targetPort: http
      name: http
    - port: {{ .Values.inventoryService.service.grpcPort }}
      targetPort: grpc
      name: grpc
  selector:
    app: {{ .Values.inventoryService.name }}
---
{{- if .Values.inventoryService.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.inventoryService.name }}-hpa
  namespace: {{ .Values.global.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.inventoryService.name }}
  minReplicas: {{ .Values.inventoryService.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.inventoryService.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.inventoryService.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
{{- end }}

