{{- if .Values.paymentService.enabled }}
# ==============================================================================
# PAYMENT SERVICE - DEPLOYMENT
# ==============================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.paymentService.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.paymentService.name }}
    component: microservice
    tier: backend
spec:
  replicas: {{ .Values.paymentService.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ .Values.paymentService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.paymentService.name }}
        component: microservice
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.paymentService.service.httpPort }}"
        prometheus.io/path: "/metrics"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - {{ .Values.paymentService.name }}
                topologyKey: kubernetes.io/hostname
      
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done;']
        - name: wait-for-kafka
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z kafka 29092; do echo waiting for kafka; sleep 2; done;']
        - name: wait-for-user-service
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z user-service 9090; do echo waiting for user-service; sleep 2; done;']
        - name: wait-for-product-service
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z product-service 9091; do echo waiting for product-service; sleep 2; done;']
        - name: wait-for-inventory-service
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z inventory-service 9092; do echo waiting for inventory-service; sleep 2; done;']
      
      containers:
        - name: {{ .Values.paymentService.name }}
          image: {{ .Values.global.imageRegistry }}/{{ .Values.paymentService.image.repository }}:{{ .Values.paymentService.image.tag }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.paymentService.service.httpPort }}
          env:
            - name: HTTP_PORT
              value: "{{ .Values.paymentService.service.httpPort }}"
            - name: DB_NAME
              value: "paymentdb"
            - name: OTEL_SERVICE_NAME
              value: "payment-service"
          envFrom:
            - secretRef:
                name: postgres-secret
            - secretRef:
                name: kafka-secret
            - configMapRef:
                name: app-config
          resources:
            {{- toYaml .Values.paymentService.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
            failureThreshold: 30
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 15"]
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.paymentService.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.paymentService.name }}
spec:
  type: {{ .Values.paymentService.service.type }}
  ports:
    - name: http
      port: {{ .Values.paymentService.service.httpPort }}
      targetPort: http
  selector:
    app: {{ .Values.paymentService.name }}

---
{{- if .Values.paymentService.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.paymentService.name }}-hpa
  namespace: {{ .Values.global.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.paymentService.name }}
  minReplicas: {{ .Values.paymentService.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.paymentService.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.paymentService.autoscaling.targetCPUUtilizationPercentage }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 50
          periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
{{- end }}

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.paymentService.name }}-pdb
  namespace: {{ .Values.global.namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ .Values.paymentService.name }}

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.paymentService.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.paymentService.name }}
  endpoints:
    - port: http
      interval: 15s
      path: /metrics
{{- end }}
