global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'full-observability'

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: []

# Load rules once and periodically evaluate them
rule_files:
  - "/etc/prometheus/rules/user_service_recording_rules.yml"
  - "/etc/prometheus/rules/user_service_alert_rules.yml"
  - "/etc/prometheus/rules/product_service_recording_rules.yml"
  - "/etc/prometheus/rules/product_service_alert_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # User Service
  - job_name: 'user-service'
    scrape_interval: 10s
    static_configs:
      - targets: ['user-service:8080']
        labels:
          service: 'user-service'
          environment: 'development'
    metrics_path: '/metrics'

  # Product Service
  - job_name: 'product-service'
    scrape_interval: 10s
    static_configs:
      - targets: ['product-service:8081']
        labels:
          service: 'product-service'
          environment: 'development'
    metrics_path: '/metrics'

  # Inventory Service
  - job_name: 'inventory-service'
    scrape_interval: 10s
    static_configs:
      - targets: ['inventory-service:8082']
        labels:
          service: 'inventory-service'
          environment: 'development'
    metrics_path: '/metrics'

