# ==============================================================================
# ANSIBLE INVENTORY - KUBERNETES CLUSTER
# ==============================================================================
# Purpose: Define target hosts and groups for Ansible automation
# ==============================================================================

all:
  children:
    # ==========================================================================
    # KUBERNETES CONTROL PLANE
    # ==========================================================================
    k8s_control_plane:
      hosts:
        k8s-master-1:
          ansible_host: 10.0.1.10
          ansible_user: ubuntu
      
      vars:
        node_type: control-plane
        k8s_role: master
    
    # ==========================================================================
    # KUBERNETES WORKER NODES
    # ==========================================================================
    k8s_workers:
      children:
        # General worker nodes (microservices)
        k8s_workers_general:
          hosts:
            k8s-worker-1:
              ansible_host: 10.0.1.11
            k8s-worker-2:
              ansible_host: 10.0.1.12
            k8s-worker-3:
              ansible_host: 10.0.1.13
          
          vars:
            node_type: worker
            node_group: general
            node_labels:
              role: general
              workload: microservices
        
        # Observability nodes (Prometheus, Grafana, Jaeger)
        k8s_workers_observability:
          hosts:
            k8s-worker-obs-1:
              ansible_host: 10.0.1.21
            k8s-worker-obs-2:
              ansible_host: 10.0.1.22
          
          vars:
            node_type: worker
            node_group: observability
            node_labels:
              role: observability
              workload: monitoring
            node_taints:
              - key: observability
                value: "true"
                effect: NoSchedule
    
    # ==========================================================================
    # DATABASE SERVERS (if not using managed services)
    # ==========================================================================
    databases:
      children:
        postgresql_servers:
          hosts:
            postgres-1:
              ansible_host: 10.0.2.10
              postgres_role: primary
            postgres-2:
              ansible_host: 10.0.2.11
              postgres_role: replica
          
          vars:
            db_port: 5432
            db_version: "15"
        
        redis_servers:
          hosts:
            redis-1:
              ansible_host: 10.0.2.20
          
          vars:
            redis_port: 6379
        
        kafka_servers:
          hosts:
            kafka-1:
              ansible_host: 10.0.2.30
            kafka-2:
              ansible_host: 10.0.2.31
            kafka-3:
              ansible_host: 10.0.2.32
          
          vars:
            kafka_port: 9092
    
    # ==========================================================================
    # LOCALHOST (for kubectl/helm commands)
    # ==========================================================================
    localhost:
      hosts:
        local:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
  
  # ============================================================================
  # GLOBAL VARIABLES
  # ============================================================================
  vars:
    # Project
    project_name: full-observability
    environment: development
    
    # Kubernetes
    k8s_version: "1.28"
    k8s_namespace: observability
    
    # Container registry
    docker_registry: docker.io
    docker_registry_username: "{{ lookup('env', 'DOCKER_USERNAME') }}"
    
    # Helm
    helm_release_name: full-observability
    helm_chart_path: ../helm/full-observability
    
    # Istio
    istio_version: "1.20.2"
    istio_profile: default

