apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secrets.database.username }}
  POSTGRES_PASSWORD: {{ .Values.secrets.database.password }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database }}
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_SSLMODE: {{ .Values.secrets.database.sslmode }}
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  JWT_SECRET_KEY: {{ .Values.secrets.jwt.secretKey }}
  JWT_EXPIRATION: {{ .Values.secrets.jwt.expiration }}
  JWT_ISSUER: {{ .Values.secrets.jwt.issuer }}
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  REDIS_ADDR: "redis:6379"
  REDIS_PASSWORD: {{ .Values.secrets.redis.password | quote }}
  REDIS_DB: "0"
---
apiVersion: v1
kind: Secret
metadata:
  name: kafka-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  KAFKA_BROKERS: {{ include "full-observability.kafkaBootstrap" . }}
  ZOOKEEPER_CONNECT: "zookeeper:2181"
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: {{ .Values.grafana.auth.adminUser }}
  GF_SECURITY_ADMIN_PASSWORD: {{ .Values.grafana.auth.adminPassword }}

