{{- if .Values.jaeger.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: {{ .Values.global.namespace }}
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: {{ .Values.global.imageRegistry }}/{{ .Values.jaeger.image.repository }}:{{ .Values.jaeger.image.tag }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.jaeger.service.collectorPort }}
              name: collector
            - containerPort: {{ .Values.jaeger.service.queryPort }}
              name: query
            - containerPort: 5778
              name: configs
            - containerPort: 6831
              protocol: UDP
              name: jaeger-thrift
            - containerPort: 14250
              name: grpc
          env:
            - name: COLLECTOR_ZIPKIN_HOST_PORT
              value: ":9411"
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
          resources:
            {{- toYaml .Values.jaeger.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: 14269
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 14269
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: {{ .Values.global.namespace }}
  labels:
    app: jaeger
spec:
  type: {{ .Values.jaeger.service.type }}
  ports:
    - port: {{ .Values.jaeger.service.collectorPort }}
      targetPort: {{ .Values.jaeger.service.collectorPort }}
      protocol: TCP
      name: collector
    - port: {{ .Values.jaeger.service.queryPort }}
      targetPort: {{ .Values.jaeger.service.queryPort }}
      {{- if eq .Values.jaeger.service.type "NodePort" }}
      nodePort: {{ .Values.jaeger.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: query
    - port: 5778
      targetPort: 5778
      name: configs
    - port: 6831
      targetPort: 6831
      protocol: UDP
      name: jaeger-thrift
    - port: 14250
      targetPort: 14250
      name: grpc
  selector:
    app: jaeger
{{- end }}

